find . -iname 'duplication_levels.png' | sort >> meta_reporte.html
find . -iname 'kmer_profiles.png' | sort >> meta_reporte.html
find . -iname 'per_base_gc_content.png' | sort >> meta_reporte.html
find . -iname 'per_base_n_content.png' | sort >> meta_reporte.html
find . -iname 'per_base_quality.png' | sort >> meta_reporte.html
find . -iname 'per_base_sequence_content.png' | sort >> meta_reporte.html
find . -iname 'per_sequence_gc_content.png' | sort >> meta_reporte.html
find . -iname 'per_sequence_quality.png' | sort >> meta_reporte.html
find . -iname 'sequence_length_distribution.png' | sort >> meta_reporte.html
